### ISSUE TITLE
12 UNIMPLEMENTED when trying to buy btc

### ISSUE THREAD

**Issue by nybe** [sparkswap/sparkswap-desktop#1]
<img width="1092" alt="Screen Shot 2019-09-18 at 7 01 44 PM" src="https://user-images.githubusercontent.com/4483720/65207548-cdfd3480-da46-11e9-9351-f706bf881aea.png">
use your app... I've jumped though the hoops to get money into it but every time I try to buy BTC I get this: 

> Failed to execute trade: 12 UNIMPLEMENTED: unknown service invoicesrpc.invoice

**Comment by dannypaz** [comment]
@nybe what wallet are you running? (lightning app, nodelauncher, etc).

**Comment by dannypaz** [comment]
@nybe I'm assuming you are using `lightning app` as your lightning node. Lightning App is not supported for the time being (unfortunately we had communication that stated otherwise). The reason is that Lightning App builds a non-standard version of lnd that does not include a handful of rpcs (`invoicesrpc`).

You can see the code point here: https://github.com/lightninglabs/lightning-app/blob/edb86d01bdfec4eef24aa19db507c6c9d8b4d78e/assets/script/install_lnd.sh#L23

Ping us on Discord or email support@sparkswap.com and we can help you further

**Comment by dannypaz** [comment]
Changed the title and leaving this issue open so that other users can find the information

**Comment by nybe** [comment]
Thanks for the response...
What would you recommend for LND on Mac? I've never been able to get Node Launcher to work...

**Comment by nybe** [comment]
I switched to using Zap Wallet and still getting errors... `The destination address for this... does not match the registered address for this account`

**Comment by dannypaz** [comment]
@nybe This is an account setup issue (since you registered with a different lnd node first). I can help you out with this either through support@sparkswap.com or hop on [our discord](https://sparkswap.com/chat)

**Comment by raymonddurk** [comment]
I am also getting that error on zap

**Comment by dannypaz** [comment]
@nybe @raymonddurk we're doing testing on lightning app, but this should be fixed on Lightning App 0.5.7 

https://github.com/lightninglabs/lightning-app/pull/1307#issuecomment-534580595

**EDIT:** Lightning App v0.5.7+ looks GTG. https://twitter.com/sparkswap/status/1176589957965594624

**Comment by raymonddurk** [comment]
Awesome. Updating the app now and will report back if I run into any bugs.
